# Site settings
title: Dan Green Leipciger’s Blog
header-img: img/home-bg.jpg
copyright_name: Dan Green-Leipciger
description: “Dan Green-Leipciger’s Blog“
baseurl: ""
github_username:  dangreenisrael

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
